import matplotlib.pyplot as plt
import pandas as pd
import argparse


# Process parameters

# Initialize parser
parser = argparse.ArgumentParser(
    description="This proram generates SNP-density plots from\na SNP density table generated by vcftools\n\n"
)

# Adding argument
parser.add_argument(
    "-i",
    "--input",
    help="SNP density file (snpden)",
    type=str,
    required=False,
    default="all.snpden",
)
parser.add_argument(
    "-o",
    "--output_prefix",
    help="output prefix",
    type=str,
    required=False,
    default="all",
)
parser.add_argument(
    "-p",
    "--plot_type",
    help="Plot type [1: snp_density+read-depth; \
            2: norm_snp_density+read-depth; \
            3: snp_density+read_coverage; \
            4: snp_density+read-depth+read_coverage+median_snp_density_line]",
    type=int,
    required=False,
    default=4,
)
args = parser.parse_args()
input_file = args.input
outputPrefix = args.output_prefix
plot_type = args.plot_type


# Read snpden file
df = pd.read_csv(input_file, sep="\t")
prefix = str(input_file).replace(".snpden", "")
prefix = prefix.replace("../", "")
df["IDX"] = df.index


chrom_ids = sorted(set(df["CHROM"]))
chrom_pos = []
x_labels = []
x_labels_pos = []
for chr in chrom_ids:
    xmax = max(df.loc[df["CHROM"] == chr, "IDX"])
    xmin = min(df.loc[df["CHROM"] == chr, "IDX"])
    xmean = int((xmax - xmin) / 2)
    chrom_pos.append(max(df.loc[df["CHROM"] == chr, "IDX"]))
    x_labels.append(chr)
    x_labels_pos.append(xmin + xmean)


if df["SNP_COUNT"].median() < 35:
    y_max = 35  # df["SNP_COUNT"].median() + (3 * df["SNP_COUNT"].std())
else:
    y_max = 700  # df["SNP_COUNT"].max() + 10

if plot_type == 1:
    fig, ax = plt.subplots(figsize=(24, 5))
    ax2 = ax.twinx()
    counter = 0
    for chr in chrom_ids:
        df2 = df.loc[df["CHROM"] == chr]
        df2.plot(
            x="IDX",
            y="SNP_COUNT",
            kind="scatter",
            color=["blue", "black"][(counter % 2)],
            ax=ax,
            s=2,
        )
        counter = counter + 1

    df.plot(
        x="IDX",
        y="COVERAGE",
        kind="line",
        color="green",
        alpha=0.3,
        ax=ax2,
        legend=None,
    )
    ax.set_xmargin(0)
    ax.set_ymargin(1)
    ax.set_ylabel(f"{prefix}\nSNP Density / 10kb")
    ax.set_ylim(0, y_max)
    ax2.set_ylabel("Mean Read Depth / 10kb")
    ax2.set_ylim(0, 200)
    ax.vlines(chrom_pos, ymin=-10, ymax=150, linestyle=":")
    ax.set_xticks(x_labels_pos)
    ax.set_xticklabels(x_labels)
    ax.set_xlabel("Chromosome")
    plt.savefig(f"{outputPrefix}.SNP_density.pdf")


if plot_type == 2:
    fig, ax = plt.subplots(figsize=(24, 4))
    ax2 = ax.twinx()
    counter = 0
    for chr in chrom_ids:
        df2 = df.loc[df["CHROM"] == chr]
        df2.plot(
            x="IDX",
            y="NORM_SNP_COUNT",
            kind="scatter",
            color=["blue", "black"][(counter % 2)],
            ax=ax,
            s=2,
        )
        counter = counter + 1

    df.plot(
        x="IDX",
        y="COVERAGE",
        kind="line",
        color="green",
        alpha=0.3,
        ax=ax2,
        legend=None,
    )
    ax.set_xmargin(0)
    ax.set_ymargin(1)
    ax.set_ylabel(f"{prefix}\nNorm. SNP Density / 10kb")
    ax.set_ylim(0, y_max)
    ax2.set_ylabel("Mean Read Depth / 10kb")
    ax2.set_ylim(0, 200)
    ax.vlines(chrom_pos, ymin=-10, ymax=150, linestyle=":")
    ax.set_xticks(x_labels_pos)
    ax.set_xticklabels(x_labels)
    ax.set_xlabel("Chromosome")
    plt.savefig(f"{outputPrefix}.SNP_density.pdf")


if plot_type == 3:
    fig, ax = plt.subplots(figsize=(24, 4))
    ax2 = ax.twinx()
    counter = 0
    for chr in chrom_ids:
        df2 = df.loc[df["CHROM"] == chr]
        df2.plot(
            x="IDX",
            y="SNP_COUNT",
            kind="scatter",
            color=["blue", "black"][(counter % 2)],
            ax=ax,
            s=2,
        )
        counter = counter + 1

    df.plot(
        x="IDX",
        y="WINDOW_COV",
        kind="line",
        color="grey",
        alpha=0.3,
        ax=ax2,
        legend=None,
    )
    ax.set_xmargin(0)
    ax.set_ymargin(1)
    ax.set_ylabel(f"{prefix}\nSNP Density / 10kb")
    ax.set_ylim(0, y_max)
    ax2.set_ylabel("Read Coverage / 10kb (%)")
    ax2.set_ylim(0, 110)
    ax.vlines(chrom_pos, ymin=-10, ymax=150, linestyle=":")
    ax.set_xticks(x_labels_pos)
    ax.set_xticklabels(x_labels)
    ax.set_xlabel("Chromosome")
    plt.savefig(f"{outputPrefix}.SNP_density.pdf")

if plot_type == 4:
    y_median_list = list()
    fig, ax = plt.subplots(figsize=(24, 4),)
    fig.subplots_adjust(right=0.75)
    ax2 = ax.twinx()
    ax3 = ax.twinx()
    counter = 0
    for chr in chrom_ids:
        df2 = df.loc[df["CHROM"] == chr]
        df3 = df2.loc[df2["SNP_COUNT"] > -1]
        y_median = df3["SNP_COUNT"].median()
        y_median_list.append(y_median)
        print(f"Median SNP density for chr {chr} = {y_median}")
        df2.plot(
            x="IDX",
            y="SNP_COUNT",
            kind="scatter",
            color=["blue", "black"][(counter % 2)],
            ax=ax,
            s=2,
        )
        counter = counter + 1
        if df3.index.size > 0:
            ax.hlines(
                y_median,
                xmin=min(df2.index),
                xmax=max(df2.index),
                linestyle="--",
                alpha=0.7,
                color="red",
            )

    df.plot(
        x="IDX",
        y="WINDOW_COV",
        kind="line",
        color="grey",
        alpha=0.3,
        ax=ax2,
        legend=None,
    )
    df.plot(
        x="IDX",
        y="COVERAGE",
        kind="line",
        color="green",
        alpha=0.3,
        ax=ax3,
        legend=None,
    )
    ax3.spines["right"].set_position(("axes", 1.05))
    ax.set_xmargin(0)
    # ax.set_ymargin(20)
    ax.set_ylabel(f"{prefix}\nSNP Density / 10kb")
    if max(y_median_list) > 35:
        y_max = 700
    ax.set_ylim(-0.3, y_max)
    ax2.set_ylabel("Read Coverage / 10kb (%)", color="grey")
    ax2.set_ylim(0, 110)
    ax2.set_xmargin(0)
    ax3.set_ylabel("Read Depth / 10kb", color="green")
    ax3.set_ylim(0, max(df["COVERAGE"] + 10))
    ax3.set_xmargin(0)
    ax.vlines(chrom_pos, ymin=-5, ymax=y_max, linestyle=":")
    ax.set_xticks(x_labels_pos)
    ax.set_xticklabels(x_labels)
    ax.set_xlabel("Chromosome")
    plt.savefig(f"{outputPrefix}.SNP_density.pdf")

